# Generated by Django 5.2.17 on 2026-09-18 18:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=160, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('kind', models.CharField(choices=[('league', 'League'), ('cup', 'Cup'), ('international', 'International')], default='league', max_length=16)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('source_license', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=160, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('source_license', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=160, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('source_license', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FootballMatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=160, unique=True)),
                ('played_on', models.DateField()),
                ('regulation_home_goals', models.PositiveSmallIntegerField()),
                ('regulation_away_goals', models.PositiveSmallIntegerField()),
                ('final_home_goals', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('final_away_goals', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('went_extra_time', models.BooleanField(default=False)),
                ('went_to_penalties', models.BooleanField(default=False)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('source_license', models.CharField(blank=True, max_length=160)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='content.competition')),
            ],
            options={
                'ordering': ['-played_on'],
            },
        ),
        migrations.CreateModel(
            name='MatchLineup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('formation', models.CharField(blank=True, max_length=20)),
                ('football_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='content.footballmatch')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineups', to='content.team')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('hangman', 'Hangman'), ('career_path', 'Career path'), ('timed_trivia', 'Timed trivia'), ('historical_score', 'Historical score'), ('missing_lineup', 'Missing lineup')], max_length=24)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('approved', 'Approved'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_questions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_payload', models.JSONField(default=dict)),
                ('answer_data', models.JSONField(default=dict)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payload', to='content.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=160, unique=True)),
                ('label', models.CharField(max_length=40)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seasons', to='content.competition')),
            ],
            options={
                'ordering': ['-start_year', 'label'],
            },
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='content.season'),
        ),
        migrations.CreateModel(
            name='SourceReference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=80)),
                ('url', models.URLField(max_length=500)),
                ('license_name', models.CharField(max_length=160)),
                ('license_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('blocked', 'Blocked')], default='pending', max_length=12)),
                ('accessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-accessed_at'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'url'), name='unique_source_provider_url')],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='source_references',
            field=models.ManyToManyField(blank=True, related_name='questions', to='content.sourcereference'),
        ),
        migrations.CreateModel(
            name='AnswerAlias',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('player', 'Player'), ('team', 'Team'), ('term', 'Term')], max_length=12)),
                ('entity_external_id', models.CharField(max_length=160)),
                ('language', models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English')], max_length=2)),
                ('alias', models.CharField(max_length=160)),
                ('normalized_alias', models.CharField(max_length=160)),
                ('source_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.sourcereference')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCareerEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=160, unique=True)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('transfer_type', models.CharField(blank=True, max_length=40)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='career_entries', to='content.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='career_entries', to='content.team')),
            ],
            options={
                'ordering': ['player', 'start_year'],
            },
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='content.team'),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='content.team'),
        ),
        migrations.CreateModel(
            name='LineupSlot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=24)),
                ('is_starter', models.BooleanField(default=True)),
                ('slot_order', models.PositiveSmallIntegerField()),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='content.matchlineup')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineup_slots', to='content.player')),
            ],
            options={
                'ordering': ['slot_order'],
                'constraints': [models.UniqueConstraint(fields=('lineup', 'slot_order'), name='unique_lineup_slot_order')],
            },
        ),
        migrations.CreateModel(
            name='QuestionTranslation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English')], max_length=2)),
                ('prompt', models.TextField()),
                ('choices', models.JSONField(blank=True, default=list)),
                ('hints', models.JSONField(blank=True, default=list)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.question')),
            ],
            options={
                'ordering': ['language'],
                'constraints': [models.UniqueConstraint(fields=('question', 'language'), name='unique_question_translation_language')],
            },
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.CheckConstraint(condition=models.Q(('end_year__gte', models.F('start_year'))), name='season_years_are_ordered'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['status', 'mode'], name='content_que_status_d2d7fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='answeralias',
            constraint=models.UniqueConstraint(fields=('entity_type', 'entity_external_id', 'language', 'normalized_alias'), name='unique_answer_alias'),
        ),
        migrations.AddConstraint(
            model_name='playercareerentry',
            constraint=models.CheckConstraint(condition=models.Q(('end_year__isnull', True), ('end_year__gte', models.F('start_year')), _connector='OR'), name='career_years_are_ordered'),
        ),
        migrations.AddConstraint(
            model_name='matchlineup',
            constraint=models.UniqueConstraint(fields=('football_match', 'team'), name='unique_match_lineup_team'),
        ),
        migrations.AddConstraint(
            model_name='footballmatch',
            constraint=models.CheckConstraint(condition=models.Q(('home_team', models.F('away_team')), _negated=True), name='football_match_teams_differ'),
        ),
    ]
