# Generated by Django 5.2.17 on 2026-09-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='seed_key',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='questiontranslation',
            name='public_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
