# Generated by Django 5.2.17 on 2026-09-18 19:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0004_match_result_match_room_code_match_settings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=1000)),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating', '-matches_played', 'user__display_name'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('global', 'Global'), ('season', 'Season')], max_length=12)),
                ('period_key', models.CharField(max_length=16)),
                ('rank', models.PositiveIntegerField()),
                ('rating', models.PositiveIntegerField()),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['period', 'period_key', 'rank'],
                'constraints': [models.UniqueConstraint(fields=('period', 'period_key', 'user'), name='unique_leaderboard_snapshot_user')],
            },
        ),
        migrations.CreateModel(
            name='RatingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_rating', models.IntegerField()),
                ('new_rating', models.IntegerField()),
                ('delta', models.IntegerField()),
                ('outcome', models.CharField(choices=[('win', 'Win'), ('draw', 'Draw'), ('loss', 'Loss')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rating_events', to='quiz.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rating_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'user_id'],
                'constraints': [models.UniqueConstraint(fields=('match', 'user'), name='unique_rating_event_match_user')],
            },
        ),
    ]
