# Generated by Django 5.2.17 on 2026-09-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameIndex(
            model_name='guestsession',
            new_name='accounts_gu_expires_4de899_idx',
            old_name='accounts_gu_expire_5c2cf3_idx',
        ),
    ]
