# Generated by Django 5.2.17 on 2026-09-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='match',
            new_name='quiz_match_status_15e1bd_idx',
            old_name='quiz_match_status_410fd1_idx',
        ),
    ]
