# Generated by Django 5.2.17 on 2026-09-18 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_question_seed_key_questiontranslation_public_data'),
        ('quiz', '0002_rename_quiz_match_status_410fd1_idx_quiz_match_status_15e1bd_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='private_state',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='round',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rounds', to='content.question'),
        ),
        migrations.AlterField(
            model_name='match',
            name='origin',
            field=models.CharField(choices=[('matchmaking', 'Matchmaking'), ('invite', 'Invite'), ('room', 'Room'), ('practice', 'Practice')], default='invite', max_length=20),
        ),
    ]
